name: metadata-cleaner # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: metadata-cleaner
license: GPL-3.0+
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo

parts:
  mat2:
    source: https://0xacab.org/jvoisin/mat2.git
    source-tag: '0.13.4'
    plugin: python
    prime:
      # WORKAROUND: Skip venv from python plugin
      - -usr/bin/activate
      - -usr/bin/activate.csh
      - -usr/bin/activate.fish
      - -usr/bin/Activate.ps1
      - -usr/bin/python
      - -usr/bin/python3
      - -usr/bin/python3.10
      - -usr/bin/pip
      - -usr/bin/pip3
      - -usr/bin/pip3.10
      - -usr/bin/wheel
      - -usr/lib/python3.10/dist-packages/pip*
      - -usr/lib/python3.10/dist-packages/pkg_resources
      - -usr/lib/python3.10/dist-packages/setuptools*
      - -pyvenv.cfg
      - -lib
      - -lib64
      - -include
      - -share
    organize:
      bin: usr/bin
      lib/python3.10/site-packages: usr/lib/python3/dist-packages
  metadata-cleaner:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://gitlab.com/rmnvgr/metadata-cleaner.git
    source-tag: v2.5.3
    meson-parameters:
      - --prefix=/snap/metadata-cleaner/current/usr
    organize:
      snap/metadata-cleaner/current: .
    parse-info: [usr/share/metainfo/fr.romainvigier.MetadataCleaner.metainfo.xml]
  deps:
    plugin: nil
    stage-packages:
      - media-types
      - libpoppler118
      - libimage-exiftool-perl
    prime:
      - usr/share/mime.types
      - usr/lib/$CRAFT_ARCH_TRIPLET/libpoppler.so.118
      - usr/lib/$CRAFT_ARCH_TRIPLET/libpoppler.so.118.0.0
      - usr/bin/exiftool
    organize:
      etc/mime.types: usr/share/mime.types
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - metadata-cleaner
      - mat2
      - deps
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - gnome-42-2204
      - gtk-common-themes
      - core22
    override-prime: |
      set -eux
      for snap in "core22" "gnome-42-2204" "gtk-common-themes"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

plugs:
  ffmpeg-2204:
    interface: content
    target: ffmpeg-platform
    default-provider: ffmpeg-2204
slots:
  metadata-cleaner:
    interface: dbus
    bus: session
    name: fr.romainvigier.MetadataCleaner
apps:
  metadata-cleaner:
    command: usr/bin/metadata-cleaner
    desktop: usr/share/applications/fr.romainvigier.MetadataCleaner.desktop
    extensions: [gnome]
    environment:
      PYTHONPATH: ${SNAP}/usr/lib/python3/dist-packages
    plugs:
      - home
      - removable-media
      - mount-observe
    common-id: fr.romainvigier.MetadataCleaner
