name: 🧪 Test snap can be built on x86_64

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: snapcore/action-build@v1
        id: snapcraft-build

#      - uses: diddlesnaps/snapcraft-review-action@v1
#        with:
#          snap: ${{ steps.snapcraft-build.outputs.snap }}
#          isClassic: 'false'
#          # Plugs and Slots declarations to override default denial (requires store assertion to publish)
#          # plugs: ./plug-declaration.json
          # slots: ./slot-declaration.json
      - uses: actions/upload-artifact@v3
        with:
          name: snap
          path: ${{ steps.snapcraft-build.outputs.snap }}
#      - name: Upload and release Metadata Cleaner Snap
#        uses: snapcore/action-publish@v1
#        env:
#          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
#        with:
#          snap: ${{ steps.snapcraft-build.outputs.snap }}
#          release: ${{ startsWith(github.ref, 'refs/tags/') && 'candidate' || 'edge'}}
